### PR TITLE
Added a new C++ fizzbuzz code

### PR DESCRIPTION
**Pull request by deepak2107**

### CODE REVIEW

**Comment by 5h0bh4nk** [comment]
Does it work normally ??

**Comment by deepak2107** [comment]
Yes!! It runs perfectly fine.

**Comment by 5h0bh4nk** [comment]
i guess it gives fizzbuzz only for powers of 2

**Comment by 5h0bh4nk** [comment]
please rectify and let me know

**Comment by 5h0bh4nk** [comment]
nice use of maps XD

**Pull request merged**
