### PR TITLE
Added Code for FIzzBuzz

### PR DESCRIPTION
**Pull request by harshit135**
FizzBuzz Code without mod operation and counting.

### CODE REVIEW

**Comment by harshit135** [comment]
Added code for FIzzBuzz without mod operation and counting.

**Comment by 5h0bh4nk** [comment]
@harshit135 numbers having 3 and 5 as factors should print FizzBuzz .

**Comment by 5h0bh4nk** [comment]
Can u please make that change and commit again so that i merge it .

**Comment by harshit135** [comment]
Okk i do it again

**Comment by 5h0bh4nk** [comment]
Thank u @harshit135 for the contribution!!
It matters !!

**Pull request merged**
