### PR TITLE
add  code of FizzBuzz 2 code in java 2 in puthon 2 in c++ all code is…

### PR DESCRIPTION
**Pull request by Ashwanigupta9125**
… easy to understand and implementable

### CODE REVIEW

**Comment by lokeshtejavath** [comment]
the fizzbuzz_easy _understand2.cpp code in C++ folder seems like it's a java code

**Comment by Ashwanigupta9125** [comment]
> the fizzbuzz_easy _understand2.cpp code in C++ folder seems like it's a java code

sorry about that but now I fix that code,can u plz check that code

**Comment by Ashwanigupta9125** [comment]
> the fizzbuzz_easy _understand2.cpp code in C++ folder seems like it's a java code

i am new in git and i don't know how to make pull request ,i change all all code in new branch but now i don't know to to make pull request with that branch
help me to make a pull request

**Comment by 5h0bh4nk** [comment]
@Ashwanigupta9125 u can view the changes in your forked repo and there , u will be seeing an option to contribute to the main repo and on clicking , u can open a pull request .

**Comment by 5h0bh4nk** [comment]
And @Ashwanigupta9125 , the codes are almost similar to the previously written codes , so it would be better if you edit existing codes rather than putting new ones .

**Comment by 5h0bh4nk** [comment]
Thank you for your PR!
Unfortunately a solution similar to yours has already been submitted :/
The goal is to find creative/abstract new solutions to FizzBuzz.
Please consult the readme for more information .
Thanks anyway! :)

**Pull request closed without merging**
