### PR TITLE
added fizzbuzz obfuscated in C++

### PR DESCRIPTION
**Pull request by GauravPoosarla**

### CODE REVIEW

**Comment by 5h0bh4nk** [comment]
Hey 👋 
Thnx for the PR !!
I was eager to know actually. 
Can u pls elaborate on how to run ur cpp code

**Comment by GauravPoosarla** [comment]
@5h0bh4nk You can run the code normally in any editor, It would work!

**Comment by 5h0bh4nk** [comment]
Yup actually i copied it wrong

**Comment by 5h0bh4nk** [comment]
Grt work @GauravPoosarla !!
Thanks for contributing 😁

**Comment by GauravPoosarla** [comment]
@5h0bh4nk I want to add more can I create multiple pr's.

**Comment by 5h0bh4nk** [comment]
Yup sure!!

**Comment by GauravPoosarla** [comment]
okay cool!

**Pull request merged**
