### PR TITLE
added fizzbuzz in new esoteric language i.e. deadfish(.xckd)

### PR DESCRIPTION
**Pull request by sriyasync**
Please view it properly before marking it invalid!

### CODE REVIEW

**Comment by 5h0bh4nk** [comment]
😂😂

**Comment by 5h0bh4nk** [comment]
@sriyasync i know about esolangs 
Dont worry !

**Comment by 5h0bh4nk** [comment]
Thanks for contributing 😁

**Comment by 5h0bh4nk** [comment]
I hope its fine 🙂

**Comment by sriyasync** [comment]
> I hope its fine 🙂

Thanks a lot!

**Pull request merged**
