### PR TITLE
problem : unique number 2n + 1

### PR DESCRIPTION
**Pull request by coder-mohan**
given a list of numbers where every numbers occurs twice except one ,we have to  find the unique number ?

### CODE REVIEW

**Review by 5h0bh4nk — COMMENTED** [review]
Spam

**Comment by coder-mohan** [comment]
@5h0bh4nk if you don't know the code then it does not it's a spam .

**Comment by 5h0bh4nk** [comment]
@coder-mohan 
How is this related to FizzBizz?
Please consult the ReadMe before submitting PR's.
Opening off-topic PR's like that is considered spam and may lead to a disqualification from Hacktoberfest.

**Review by lokeshtejavath — COMMENTED** [review]
hey @coder-mohan we surely know what the code does, but our capabilities are not enough to let us see how finding unique numbers in an array leads to fizzbuzz
Do let us know how it is until then it's going to be marked spam.

Also a small word of advice, check out readme of a repo to understand what a repo actually wants.
Thank you!

**Comment by 5h0bh4nk** [comment]
Open source community still welcomes you @coder-mohan . Hope u contribute to it well 😁 . 
With this , i think we can close this PR .

**Pull request closed without merging**
