### PR TITLE
Added some elixir fizz buzz solutions

### PR DESCRIPTION
**Pull request by ryguigas0**
Fizz buzz code in elixir!

### CODE REVIEW

**Comment by 5h0bh4nk** [comment]
u would like all commits to be merged in 1 PR or multiple ??

**Comment by 5h0bh4nk** [comment]
the solutions lokk pretty good

**Comment by ryguigas0** [comment]
Nah just one, thanks for checking it!

**Comment by ryguigas0** [comment]
If I think of any weirder solutions I'll be sure to send it!

**Comment by 5h0bh4nk** [comment]
Sure . Thank u @ryguigas0 for contribution.
We highly appreciate your efforts !

**Pull request merged**
